[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite']
hook_source = '''
" Custom map
call denite#custom#map('insert', "<C-p>", '<denite:move_to_previous_line>', 'noremap')
call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>', 'noremap')

" Custom Source
call denite#custom#var('grep', 'command', ['git', '--no-pager', 'grep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#var('grep', 'separator', [])
call denite#custom#var('grep', 'default_opts', ['-nH'])
'''
hook_add = '''
nmap , [denite]

nnoremap [denite]f :<C-u>Denite file<CR>
nnoremap [denite]bf :<C-u>Denite buffer<CR>
nnoremap [denite]bk :<C-u>Denite bookmark<CR>
nnoremap [denite]r :<C-u>Denite file_mru<CR>
nnoremap [denite]a :<C-u>Denite file buffer file_mru<CR>
nnoremap [denite]<Tab> :<C-u>Denite tab<CR>
nnoremap [denite]gs :<C-u>Denite gitstatus<CR>
nnoremap [denite]gr :<C-u>Denite grep -buffer-name=search-buffer -no-quit<CR>
" カーソル位置の単語をgrep検索
nnoremap [denite]cgr :<C-u>DeniteCursorWord grep -buffer-name=search-buffer -no-quit<CR>
nnoremap [denite]ma :<C-u>Denite mapping<CR>
nnoremap [denite]o :<C-u>Denite outline<CR>
" Execute help.
nnoremap <silent> <C-h>  :<C-u>Unite -buffer-name=help help<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'chemzqm/vim-easygit'
on_source = ['denite-git']

[[plugins]]
repo = 'chemzqm/denite-git'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
" Use deoplete.
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_source = ['deoplete.nvim']
build = 'make'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'Chiel92/vim-autoformat'
on_ft = ['typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml', 'ansible']
