[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vimproc']
on_cmd = ['Unite']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'kmnk/vim-unite-giti'
on_source = ['unite.vim']

[[plugins]]
repo = 'mattn/unite-mpc'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-session'
on_source = ['unite.vim']

[[plugins]]
repo = 'rafi/vim-unite-issue'
on_source = ['unite.vim']
depends = ['webapi-vim', 'open-browser.vim', 'unite.vim']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'Chiel92/vim-autoformat'
on_ft = ['typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml', 'ansible']

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc']
on_i = 1

[[plugins]]
repo = 'venantius/vim-cljfmt'
on_ft = ['clojure']
