[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'synic.vim'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'YankRing.vim'

[[plugins]]
repo = 'Markdown'

[[plugins]]
repo = 'textutil.vim'

[[plugins]]
repo = 'vim-niji'

[[plugins]]
repo = 'mattn/vimplenote-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/mkdpreview-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/echodoc'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'tpope/vim-pathogen'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-logcat'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-scouter'

[[plugins]]
repo = 'thinca/vim-threes'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-fireplace'

[[plugins]]
repo = 'tpope/vim-classpath'

[[plugins]]
repo = 'guns/vim-clojure-static'

[[plugins]]
repo = 'kakkyz81/evervim'

[[plugins]]
repo = 'aharisu/vim_goshrepl'

[[plugins]]
repo = 'aharisu/vim-gdev'

[[plugins]]
repo = 'ujihisa/neoclojure.vim'

[[plugins]]
repo = 'basyura/bitly.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['neosnippet']
